/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --env-file=/dev/null --include-runtime=false --env-interface=CloudflareEnv` (hash: 28f1b8e2af5f6d58760afae543ac747a)
interface __BaseEnv_CloudflareEnv {
	VAULT_FILES: R2Bucket;
	DB: D1Database;
	AUTH_RATE_LIMITER: RateLimit;
	BOOTSTRAP_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BOOTSTRAP_SECRET">> {}
}
