/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --env-file=/dev/null --include-runtime=false --env-interface=CloudflareEnv` (hash: f01013651de0dce5c1682c698dfda0e9)
interface __BaseEnv_CloudflareEnv {
	VAULT_FILES: R2Bucket;
	DB: D1Database;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
